### ISSUE TITLE
Docker container restart issue

### ISSUE THREAD

**Issue by modem7** [crowdsecurity/cs-cloudflare-worker-bouncer#50]
When I try to restart the container, it tries to clean up the worker but fails. 

```
time="2024-11-08T19:53:30Z" level=info msg="Using API key auth"
time="2024-11-08T19:53:31Z" level=info msg="Cleaning up existing workers" account=myaccount@mydomain.com
time="2024-11-08T19:53:33Z" level=fatal msg="unable to cleanup existing workers: remove namespace: 'namespace has associated scripts: crowdsec-cloudflare-worker-bouncer' (10052) for account myaccount@mydomain.com"
```

```yaml
  # CrowdSec Bouncer - Cloudflare
  # sudo docker exec crowdsec cscli bouncer add cloudflare-worker-bouncer
  # To recover: docker run --rm -it -v "$(pwd)"/cfg.yaml:/etc/crowdsec/bouncers/crowdsec-cloudflare-worker-bouncer.yaml --name WorkerBouncerRecovery 'crowdsecurity/cloudflare-worker-bouncer' -d
  cloudflare-worker-bouncer:
    image: crowdsecurity/cloudflare-worker-bouncer
    container_name: Crowdsec-Cloudflare-Worker-Bouncer
    networks:
      pihole:
        ipv4_address: '172.22.0.125'
    # ports:
    #  - "2112:2112"
    volumes:
      - $USERDIR/Crowdsec/cloudflare-worker-bouncer/cfg.yaml:/etc/crowdsec/bouncers/crowdsec-cloudflare-worker-bouncer.yaml
      # - $USERDIR/Crowdsec/cloudflare-worker-bouncer/cf-bouncer:/cf-bouncer
    # labels:
    #   - "backup"
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    restart: always
    mem_limit: 500m
    mem_reservation: 50m
    depends_on:
      - crowdsec
```

![image](https://github.com/user-attachments/assets/905e50d9-6582-4fc0-892f-56bf833ac00b)
